version: '3.7'

services:
  wincore-release:
    image: wincore-vsts-release:0.1
    deploy:
      replicas: 1
    environment:
      - VSTS_ACCOUNT=
      - VSTS_TOKEN=
      - VSTS_POOL=
      - VSTS_AGENT={{.Node.Hostname}}{{"-wincore-release-"}}{{.Task.Slot}}
      - VSTS_PROXY_URL=
      - VSTS_HTTP_PROXY=
      - http_proxy=
      - https_proxy=
      - no_proxy={{.Node.Hostname}}
      - DOCKER_HOST={{"tcp://"}}{{.Node.Hostname}}{{":2375"}}
      - ENVIRONMENT=Development
      - RELEASE_AGENT=true
